rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::DualBoardDemo -> dual_board_demo_hardware

dual_board_demo_hardware:
  ros__parameters:
    board_serial_top_board: "(TODO)"
    board_serial_bottom_board: "(TODO)"
