rmcs_executor:
  ros__parameters:
    update_rate: 100.0
    components:
      - rmcs_core::hardware::OledDemo -> oled_demo_hardware

oled_demo_hardware:
  ros__parameters:
    board_serial: "(TODO)"
    oled_i2c_address: 60
    display_message: |
      RMCS OLED Demo
      Set /oled/text to override.
