rmcs_executor:
  ros__parameters:
    update_rate: 100.0
    components:
      - rmcs_core::hardware::OledDemo -> oled_demo_hardware

oled_demo_hardware:
  ros__parameters:
    board_serial: "d4e779"
    skip_version_checks: true
    oled_refresh_period: 20
    oled_i2c_address: 60
