rmcs_executor:
  ros__parameters:
    update_rate: 100.0
    components:
      - rmcs_core::hardware::OledMenuDemo -> oled_menu_hardware
      - rmcs_core::input::ButtonGesture -> oled_menu_button
      - rmcs_core::oled_menu::OledMenu -> oled_menu

oled_menu_hardware:
  ros__parameters:
    board_serial: "d4e779"
    skip_version_checks: true
    oled_refresh_period: 5
    oled_i2c_address: 60
    button_gpio_channel: 7
    button_read_period_ms: 10
    button_output_prefix: /button/pi7
    test_value_initial: 0

oled_menu_button:
  ros__parameters:
    raw_pressed_input: /button/pi7/raw_pressed
    output_prefix: /button/pi7
    debounce_ms: 25
    double_click_gap_ms: 0
    long_press_ms: 600

oled_menu:
  ros__parameters:
    button_prefix: /button/pi7
    test_value_initial: 0
